# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
    - restapi*
  paths:
    include:
    - sdk/voicelive/
    - sdk/core/

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
    - restapi*
  paths:
    include:
    - sdk/voicelive/
    - sdk/core/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: voicelive
    TestProxy: true
    BuildDocs: true
    TestTimeoutInMinutes: 60
    Artifacts:
    - name: azure-ai-voicelive
      safeName: azureaivoicelive
